feedback:
  url: https://docs.google.com/forms/d/1AGP5J8S4PUWa-dIkaJZTOtbmVE32fQ4MvYV4eup9KZg/viewform?embedded=true
evaluation:
  # Percentages for the suggestion of evaluation color range values
  suggestion_lower: 25
  suggestion_upper: 50
