secret_token: 84740c544474a976e444c23c1baf83aac975ef55ae36c313f3c67bd1188ea9eed1e39c9ffb92969469965a988cd59ef9b66cac9f362d6a520d4bcaf0f9419342
feedback: false

# Set to false if only one instance is used
multiple_instances: true

yubikey: false
# yubikey:
#   api_id: Your API ID
#   api_key: Your API key
#   url: Custom URL to a Yubikey validation server
#   hint: An optional hint text for the yubikey form fields

# eula:
#   header: Optional popup for an agreement that the user
#   body: needs to confirm on each login. The body supports <b>html</b>

# login_logo: logos/custom_login_logo.png

# instance_banner: Some <b>optional text</b> displayed in a banner at the top of each page
